- hosts: localhost
  connection: local
  vars:
          lacp_groups:
                  - master: lacp0
                    network: 10.65.100.0/24
                    gateway: 10.65.100.1
                    dns4:
                            - 10.65.100.10
                            - 10.65.100.11
                    interfaces:
                            - em1
                            - em2

                  - master: lacp1
                    network: 10.65.100.0/24
                    gateway: 10.155.100.2
                    dns4:
                            - 10.155.100.10
                            - 10.155.100.11
                    interfaces:
                            - em3
                            - em4
  tasks:
    - debug:
        msg: "{{ (lacp_groups|selectattr('interfaces', 'contains', 'em1')|first).master }}"
