- hosts: localhost
  connection: local
  vars:
          mylist:
                  - 1
                  - "{{ 3 == 3}}"
                  - True
          myotherlist:
                  - False
                  - True
  tasks:
          - debug:
                  msg: "all are true"
            when: mylist is all
          - debug:
                  msg: "at least one is true"
            when: myotherlist is any

