tasks:
          - name: Register JSON output as a variable
                ansible.builtin.shell: cat /some/path/to/file.json
                    register: result

                      - name: Set a variable
                            ansible.builtin.set_fact:
                                          myvar: "{{ result.stdout | from_json }}"
