- hosts: localhost
  connection: local
  vars: 
        my_version: 1.2.3
  tasks:
            - debug:
                    msg: "my version is heigher than 1.0.0"
              when: my_version is version('1.0.0', '>')

